filebeat.inputs:
- type: log
  paths:
    - /var/log/nginx/*.log
  fields:
    type: prod.product-terms.nginx.log
    environment: prod.product-terms
    service: nginx
  document_type: filebeat.nginx.product-terms
  registry: /var/lib/filebeat/registry

- type : log
  paths:
    - /var/log/php*.log
  fields:
    type: prod.product-terms.php-fpm.log
    environment: prod.product-terms
    service: php-fpm
  document_type: filebeat.php-fpm
  registry: /var/lib/filebeat/registry

- type : log
  paths:
    - /var/www/html/storage/logs/laravel.log
  fields:
    type: prod.product-terms.laravel.log
    environment: prod.product-terms
    service: laravel
  document_type: filebeat.laravel
  registry: /var/lib/filebeat/registry

output.elasticsearch:
  hosts: ["https://vpc-production-logging-s5yxpzfv42zj6v4aloblqiddxq.eu-central-1.es.amazonaws.com:443"]
  protocol: "https"

