<?php

return [
    'id'                         => ['id'],
    'trade_item_id'              => ['tradeitemid', 'trade item id', 'trade_item_id'],
    'supplier_id'                => ['SupplierId', 'supplier id', 'supplier_id'],
    'customer_group_id'          => ['CustomerGroupId', 'customer group id', 'customer_group_id'],
    'internal_name'              => ['Internal Name', 'InternalName', 'internal_name'],
    'supplier_trade_item_number' => ['SupplierTradeItemNumber', 'supplier trade item number', 'supplier_trade_item_number'],
    'stock_keeping_unit'         => ['stockkeepingunit', 'stock keeping unit', 'stock_keeping_unit'],
    'old_stock_keeping_unit'     => ['oldstockkeepingunit', 'old stock keeping unit', 'old_stock_keeping_unit'],
    'net_price'                  => ['netprice', 'net price', 'net_price'],
    'currency'                   => ['currency'],
    'sales_unit'                 => ['salesunit', 'sales unit', 'sales_unit'],
    'minimum_delivery_time'      => ['minimumdeliverytime', 'minimum delivery time', 'minimum_delivery_time'],
    'maximum_delivery_time'      => ['maximumdeliverytime', 'maximum delivery time', 'maximum_delivery_time'],
    'minimum_order_quantity'     => ['minimumorderquantity', 'minimum order quantity', 'minimum_order_quantity'],
    'maximum_order_quantity'     => ['maximumorderquantity', 'maximum order quantity', 'maximum_order_quantity'],
    'delivery_time_unit'         => ['deliverytimeunit', 'delivery time unit', 'delivery_time_unit'],
    'is_warehouse_item'          => ['iswarehouseitem', 'is warehouse item', 'is_warehouse_item'],
    'is_active'                  => ['isactive', 'is active', 'is_active'],
    'import_status'              => ['importstatus', 'import status', 'import_status'],
    'created_at'                 => ['createdat', 'created at', 'created_at'],
    'updated_at'                 => ['updatedat', 'updated at', 'updated_at'],
];
